service: jira-toggl-sync

plugins:
  - serverless-plugin-typescript
  - serverless-offline


provider:
  name: aws
  runtime: nodejs8.10

functions:
  hello:
    handler: src/functions/handler.hello
    events:
      - http:
          path: hello
          method: get